version: '3.8'

services:
  oracle19c:
    image: gvenzl/oracle-free:slim-faststart
    container_name: oracle19c
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=FREEPDB1
    volumes:
      - oracle_data:/opt/oracle/oradata
      - oracle_backup:/opt/oracle/backup
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-s", "system/oracle@//localhost:1521/XE", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - ollama_network

volumes:
  oracle_data:
    driver: local
  oracle_backup:
    driver: local

networks:
  ollama_network:
    driver: bridge
